file:
  upload:
    image:
      whiteList: gif,png,bmp,jpg,jpeg
    dir : /Users/yusuwan/Desktop/img
  upload-limit-size: 10485760


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8800

spring:
  datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:oracle:thin:@192.168.10.120:1521/xe
      password: 12345
      username: yusuwan

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    view:
      suffix: .hbs
  messages:
    basename: i18n/exception
    encoding: UTF-8
